/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev13
 */
public class deposit_GUI_110618 extends javax.swing.JFrame {

    /**
     * Creates new form deposit_GUI_110618
     */
    public deposit_GUI_110618() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_deposit = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        txt_deposit = new javax.swing.JTextField();
        btn_deposit = new javax.swing.JButton();
        txt_balance = new javax.swing.JTextField();
        lbl_balance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_deposit.setText("deposit");
        getContentPane().add(lbl_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        btn_menu.setText("main menu");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));
        getContentPane().add(txt_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, -1));

        btn_deposit.setText("deposit");
        btn_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        txt_balance.setEditable(false);
        getContentPane().add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, -1));

        lbl_balance.setText("curent balance");
        getContentPane().add(lbl_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositActionPerformed
        if(Double.parseDouble(txt_deposit.getText())>0){
        menu_GUI_110618.Account.setbalance( menu_GUI_110618.Account.getBalance()+Double.parseDouble(txt_deposit.getText()));
        txt_balance.setText(String.valueOf(menu_GUI_110618.Account.getBalance()));
        }
    }//GEN-LAST:event_btn_depositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposit_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposit_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposit_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposit_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposit_GUI_110618().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deposit;
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel lbl_balance;
    private javax.swing.JLabel lbl_deposit;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_deposit;
    // End of variables declaration//GEN-END:variables
}
