/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev13
 */
import java.util.ArrayList;
public class menu_GUI_110618 extends javax.swing.JFrame {

    
    public static Account_class_110618 Account;//is static cause we will acces the menu class without
    //creating an instance of it ...we will do that in all the jframes
///we create this object public because we want teh other frames to see it
    //i mean withdrawal ,blance ,deposit and they will all see it,account will be set when
    //we match an account from the bank list when we call the login button 
    //and there in that function fro logi button we will also have the constructor of the menu and that object
    //acount that was found will be passed to this public variable Account(basically the sxecond constructor
    //from below will do that) and then everyone will do operations on this account object
    public static atm_class_110618 AIB;
    public menu_GUI_110618(){//i think this is manadtory to create the empty constructor
        //before we create a constructor with parameters
        initComponents();///if we decide to use this then we have to initiate the menu and all its objects
        
    }
    public menu_GUI_110618(Account_class_110618 acc,atm_class_110618 aib) {//if when we login the account is found 
        //then we are passed to teh menu and when we make the menu visible(true)
        //we also initiate it there and we want when we find the right combination of account an password
        //to create menu which calls its constructor ,and we want to call the constructor
        //which takes an argument (this one right here)  and  not teh empty constructor
        //--this constructor will make sure that the account which we found is passed further 
        //to our menu so we can get the balance withrawal and all oter methods with tis saved 
        //acou8nt...the balance withdrawal and other jframes will also need this account passed 
        //for ttheir functions
        initComponents();
        Account=acc;//initiate an account and a bank object
        AIB=aib;
        //System.out.println(Account.getAccount());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_view_balance = new javax.swing.JButton();
        btn_withrawal = new javax.swing.JButton();
        btn_deposit = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        lbl_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_view_balance.setText("view balance");
        btn_view_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_balanceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        btn_withrawal.setText("withdrawal");
        btn_withrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_withrawalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_withrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 121, -1, -1));

        btn_deposit.setText("deposit");
        btn_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 165, -1, -1));

        btn_exit.setText("exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 209, -1, -1));

        lbl_menu.setText("menu");
        getContentPane().add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_view_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_balanceActionPerformed
        new view_balance_GUI_110618().setVisible(true);
    }//GEN-LAST:event_btn_view_balanceActionPerformed

    private void btn_withrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_withrawalActionPerformed
        new withdrawal_GUI_110618().setVisible(true);
    }//GEN-LAST:event_btn_withrawalActionPerformed

    private void btn_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositActionPerformed
        // TODO add your handling code here:
        new deposit_GUI_110618().setVisible(true);
    }//GEN-LAST:event_btn_depositActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        FileOperations.writeTOtextFile(AIB.listOfAccounts);
        this.setVisible(false);
        new login_GUI_110618().setVisible(true);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_GUI_110618().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deposit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_view_balance;
    private javax.swing.JButton btn_withrawal;
    private javax.swing.JLabel lbl_menu;
    // End of variables declaration//GEN-END:variables
}
