/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev13
 */
public class withdrawal_GUI_110618 extends javax.swing.JFrame {

    /**
     * Creates new form withdrawal_GUI_110618
     */
    
    public withdrawal_GUI_110618() {
        initComponents();
        txt_cur_account.setText(String.valueOf(menu_GUI_110618.Account.getBalance()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_withdrawal = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        txt_withdrawal_amount = new javax.swing.JTextField();
        lbl_cur_balance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_withdrawal = new javax.swing.JButton();
        txt_cur_account = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_withdrawal.setText("withdrawal");
        getContentPane().add(lbl_withdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        btn_menu.setText("mai menu");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));
        getContentPane().add(txt_withdrawal_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, -1));

        lbl_cur_balance.setText("curent balance");
        getContentPane().add(lbl_cur_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel2.setText("withdrawal amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        btn_withdrawal.setText("withdrawal");
        btn_withdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_withdrawalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_withdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txt_cur_account.setEditable(false);
        getContentPane().add(txt_cur_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_withdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_withdrawalActionPerformed
        if(Double.parseDouble(txt_withdrawal_amount.getText())<=menu_GUI_110618.Account.getBalance()&
                Double.parseDouble(txt_withdrawal_amount.getText())>0){   
        menu_GUI_110618.Account.setbalance( menu_GUI_110618.Account.getBalance()-Double.parseDouble(txt_withdrawal_amount.getText()));
        txt_cur_account.setText(String.valueOf(menu_GUI_110618.Account.getBalance()));
        }
    }//GEN-LAST:event_btn_withdrawalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdrawal_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdrawal_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdrawal_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdrawal_GUI_110618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdrawal_GUI_110618().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_withdrawal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_cur_balance;
    private javax.swing.JLabel lbl_withdrawal;
    private javax.swing.JTextField txt_cur_account;
    private javax.swing.JTextField txt_withdrawal_amount;
    // End of variables declaration//GEN-END:variables
}
