/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev13
 */
public class sum_acumulator_GUI_060618 extends javax.swing.JFrame {

    /**
     * Creates new form sum_acumulator_GUI_060618
     */
    int acumulator=0;
    public sum_acumulator_GUI_060618() {
        initComponents();
        txt_enterNumber.setText(String.valueOf(acumulator));
        //this will initiate the box to 0 and will also make sure that addfunction will
        //not encounter a error when it will try to do parseInt as parse "0" is 0,
        //but if we don t iniate it then parse "" willo nresult in error
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sum_acumulator = new javax.swing.JLabel();
        txt_enterNumber = new java.awt.TextField();
        txt_acumulated_value = new java.awt.TextField();
        btn_add = new java.awt.Button();
        btn_reset = new java.awt.Button();
        lbl_enter = new java.awt.Label();
        lbl_acumulated = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sum_acumulator.setText("sum acumulator");
        getContentPane().add(lbl_sum_acumulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 20, -1, -1));
        getContentPane().add(txt_enterNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 70, -1));

        txt_acumulated_value.setEditable(false);
        getContentPane().add(txt_acumulated_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 70, -1));

        btn_add.setLabel("add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 50, -1));

        btn_reset.setLabel("reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, -1));

        lbl_enter.setText("enter a number");
        getContentPane().add(lbl_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        lbl_acumulated.setText("acumulated value");
        getContentPane().add(lbl_acumulated, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        int newNumber=Integer.parseInt(txt_enterNumber.getText());
        acumulator+=newNumber;
        txt_acumulated_value.setText(String.valueOf(acumulator));
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        acumulator=0;
        txt_acumulated_value.setText("");
        txt_enterNumber.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sum_acumulator_GUI_060618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sum_acumulator_GUI_060618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sum_acumulator_GUI_060618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sum_acumulator_GUI_060618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sum_acumulator_GUI_060618().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_add;
    private java.awt.Button btn_reset;
    private java.awt.Label lbl_acumulated;
    private java.awt.Label lbl_enter;
    private javax.swing.JLabel lbl_sum_acumulator;
    private java.awt.TextField txt_acumulated_value;
    private java.awt.TextField txt_enterNumber;
    // End of variables declaration//GEN-END:variables
}
