/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev13
 */
public class applet_GUI_130618 extends javax.swing.JApplet {

    /**
     * Initializes the applet applet_GUI_130618
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applet_GUI_130618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applet_GUI_130618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applet_GUI_130618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applet_GUI_130618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_text = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_enter_txt = new javax.swing.JLabel();
        lbl_enter_word = new javax.swing.JLabel();
        txt_enter_word = new javax.swing.JTextField();
        lbl_status = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        btn_find_word = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_numWords = new javax.swing.JLabel();
        lbl_numofchar = new javax.swing.JLabel();
        lbl_num_nospaces = new javax.swing.JLabel();
        lbl_num_paragraphs = new javax.swing.JLabel();
        txt_numWords = new javax.swing.JTextField();
        txt_numChars = new javax.swing.JTextField();
        txt_numChars_no_spaces = new javax.swing.JTextField();
        txt_num_paragraphs = new javax.swing.JTextField();
        btn_word_count = new javax.swing.JButton();
        lbl_count_wordandchars = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        pane_text.setViewportView(jTextArea1);

        getContentPane().add(pane_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 110));

        lbl_enter_txt.setText("Enter text");
        getContentPane().add(lbl_enter_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lbl_enter_word.setText("Enter word");
        getContentPane().add(lbl_enter_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));
        getContentPane().add(txt_enter_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 100, -1));

        lbl_status.setText("status");
        getContentPane().add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        txt_status.setEditable(false);
        getContentPane().add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, -1));

        btn_find_word.setBackground(new java.awt.Color(255, 255, 255));
        btn_find_word.setText("find word");
        getContentPane().add(btn_find_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 90, -1));

        btn_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("clear");
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 80, -1));

        lbl_numWords.setText("number of words");
        getContentPane().add(lbl_numWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lbl_numofchar.setText("number of charachters including spaces");
        getContentPane().add(lbl_numofchar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        lbl_num_nospaces.setText("number of characters without spaces");
        getContentPane().add(lbl_num_nospaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lbl_num_paragraphs.setText("number of paragraphs");
        getContentPane().add(lbl_num_paragraphs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(txt_numWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 70, -1));

        txt_numChars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numCharsActionPerformed(evt);
            }
        });
        getContentPane().add(txt_numChars, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 70, -1));
        getContentPane().add(txt_numChars_no_spaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, -1));
        getContentPane().add(txt_num_paragraphs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 70, -1));

        btn_word_count.setText("word count");
        getContentPane().add(btn_word_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        lbl_count_wordandchars.setText("count of words and characters");
        getContentPane().add(lbl_count_wordandchars, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numCharsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numCharsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numCharsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_find_word;
    private javax.swing.JButton btn_word_count;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_count_wordandchars;
    private javax.swing.JLabel lbl_enter_txt;
    private javax.swing.JLabel lbl_enter_word;
    private javax.swing.JLabel lbl_numWords;
    private javax.swing.JLabel lbl_num_nospaces;
    private javax.swing.JLabel lbl_num_paragraphs;
    private javax.swing.JLabel lbl_numofchar;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JScrollPane pane_text;
    private javax.swing.JTextField txt_enter_word;
    private javax.swing.JTextField txt_numChars;
    private javax.swing.JTextField txt_numChars_no_spaces;
    private javax.swing.JTextField txt_numWords;
    private javax.swing.JTextField txt_num_paragraphs;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
