/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SwDev13
 */
import javax.swing.JOptionPane;
public class insurance_calc_GUI_010618 extends javax.swing.JFrame {

    /**
     * Creates new form insurance_calc_GUI_010618
     */
    String ageee="";
    String no_claim_bon="";
    String eng_size="";
    
    public insurance_calc_GUI_010618() {
        ///we initiate some default values as if we want to press tyhe calculate value buton
        //straight from the start it still displays a quote,otherwise these will have the ""
        //default value and no quote will be shown
        initComponents();
        ageee="less than 17";
        no_claim_bon="1";
        eng_size="0-2000";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        premium = new javax.swing.JTextField();
        age = new javax.swing.JComboBox<>();
        engine_size = new javax.swing.JComboBox<>();
        no_claim_bonus = new javax.swing.JComboBox<>();
        btn_calculate = new javax.swing.JButton();
        NC_bonus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        premium.setEditable(false);
        premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumActionPerformed(evt);
            }
        });
        getContentPane().add(premium, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 179, 80, -1));

        age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "less than 17", "17-21", "22-30", "31-79", "greater or = 80" }));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 125, -1, -1));

        engine_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-2000", "2001-2999", "over or = 3000" }));
        engine_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engine_sizeActionPerformed(evt);
            }
        });
        getContentPane().add(engine_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 87, -1, -1));

        no_claim_bonus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        no_claim_bonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_claim_bonusActionPerformed(evt);
            }
        });
        getContentPane().add(no_claim_bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 43, -1, -1));

        btn_calculate.setText("calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        NC_bonus.setText("noclaim bonus");
        getContentPane().add(NC_bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel2.setText("engine size");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setText("age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setText("premium");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_claim_bonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_claim_bonusActionPerformed
      //these with action performed are text boxes,and we want to retrieve the user input
      //with get and store it in a local variable which will be used for calculating premium
       no_claim_bon= no_claim_bonus.getSelectedItem().toString();
    }//GEN-LAST:event_no_claim_bonusActionPerformed

    private void engine_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engine_sizeActionPerformed
        // creates eng_size global variable..i don t know if its global i just mean its
        //scope is global as everyone can see it as engine_size is local scope
        //and eng_size can be used by the button function to calculate the premium
        eng_size=engine_size.getSelectedItem().toString();
    }//GEN-LAST:event_engine_sizeActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // creates ageee global variable:
        ageee=age.getSelectedItem().toString();
    }//GEN-LAST:event_ageActionPerformed

    private void premiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumActionPerformed
   //tis function doesn t need to do anything for us...we just want the premium 
   //displayed here
        
    }//GEN-LAST:event_premiumActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        // when the butto is pressed it will calculate the premium and set the
        //premium text field to the value of the calculated premium...if the 
        //premium can t be calculated the reason_for_no_quote string will be build
        //and displayed in a message box done with JOptionPane
        final double default_premium=1000;
        double premiumpayable=0.0;
        boolean bool_quote=true;
        String reason_for_no_quote="";
        if (ageee.equalsIgnoreCase("less than 17")){
            premiumpayable=0.0;
            bool_quote=false;
            reason_for_no_quote="less than 17";
            //reason for no quote is a string which will be built lets say we
            //have an error it will add 1 msh to string but if  we have more ,every time we
            //want to use it we concatenate to th eoriginal string so ,if less than 17 some mess will show
            ///but lets say then the engine is >3000cc 
        }
        else if(ageee.equalsIgnoreCase("17-21"))
            premiumpayable=default_premium+default_premium*0.15;
        else if(ageee.equalsIgnoreCase("22-30"))  
            premiumpayable=default_premium+default_premium*0.10;
        else if(ageee.equalsIgnoreCase("31-79"))
            premiumpayable=default_premium;
        else
            premiumpayable=default_premium+default_premium*0.22;
        
        switch(no_claim_bon){
            case "1" : premiumpayable=premiumpayable*0.95;
            case "2" : premiumpayable=premiumpayable*0.90;
            case "3" : premiumpayable=premiumpayable*0.85;
            case "4" : premiumpayable=premiumpayable*0.80;
            case "5" : premiumpayable=premiumpayable*0.75;
            default:premiumpayable=premiumpayable;//not really necesary tyhis default as it changes nothing
            
        }
        switch(eng_size){
            case "0-2000" : break;//no action is needed as it stays same
            case "2001-2999" : premiumpayable=premiumpayable+300;break;
            case "over or = 3000" : premiumpayable=0.0;bool_quote=false;reason_for_no_quote=reason_for_no_quote+"\n engine bigger or = than 3000";//we don t need to insure
            //and we set a bool so we can do a if condition that will output a  message box
            //if  any of these less than 17 or engine >3000 ocurr
        
        }
        if(bool_quote)
            
            premium.setText(String.valueOf(premiumpayable));
        //premium.setText(String.format("%.2f",premiumpayable));
        //we might want only tyeh first 2 decimals as sometimes there are huge num of decimals
        //so teh code above can be replaced with this one
        else{
            premium.setText("0.0");
            JOptionPane.showMessageDialog(this,reason_for_no_quote, "No quote", JOptionPane.INFORMATION_MESSAGE);
            //this shows messag ebox if use r not eligible for quote
            
        }
        
    }//GEN-LAST:event_btn_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insurance_calc_GUI_010618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insurance_calc_GUI_010618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insurance_calc_GUI_010618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insurance_calc_GUI_010618.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insurance_calc_GUI_010618().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NC_bonus;
    private javax.swing.JComboBox<String> age;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JComboBox<String> engine_size;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> no_claim_bonus;
    private javax.swing.JTextField premium;
    // End of variables declaration//GEN-END:variables
}
